-- Currently active (non-idle) sessions (YashanDB V$SESSION schema)
SELECT SID, SERIAL#, USERNAME, STATUS, OSUSER, PROGRAM,
       SQL_ID, WAIT_EVENT, WAIT_CLASS, LOGON_TIME
FROM V$SESSION
WHERE STATUS = 'ACTIVE'
  AND USERNAME IS NOT NULL
ORDER BY SID;
