-- Top SQL by total elapsed time from V$SQLAREA (in-memory cursor cache)
SELECT SQL_ID,
       ROUND(ELAPSED_TIME / 1000000, 2)         AS ELAPSED_SEC,
       EXECUTIONS,
       ROUND(ELAPSED_TIME / GREATEST(EXECUTIONS, 1) / 1000000, 4) AS AVG_ELAPSED_SEC,
       DISK_READS,
       BUFFER_GETS,
       ROWS_PROCESSED,
       SUBSTR(SQL_TEXT, 1, 200)                 AS SQL_TEXT_PREVIEW
FROM V$SQLAREA
WHERE EXECUTIONS > 0
ORDER BY ELAPSED_TIME DESC;
