// Command stepcatalog generates internal/runner/stepcatalog/catalog_gen.go and validates registry IDs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/yinstall/internal/runner"
	cleansteps "github.com/yinstall/internal/steps/clean"
	collectsteps "github.com/yinstall/internal/steps/collect"
	dbsteps "github.com/yinstall/internal/steps/db"
	mssqlsteps "github.com/yinstall/internal/steps/mssql"
	mssqlagsteps "github.com/yinstall/internal/steps/mssql_ag"
	mssqlmirrorsteps "github.com/yinstall/internal/steps/mssql_mirror"
	mysqlsteps "github.com/yinstall/internal/steps/mysql"
	mysqlstandbysteps "github.com/yinstall/internal/steps/mysql_standby"
	omsteps "github.com/yinstall/internal/steps/om"
	ossteps "github.com/yinstall/internal/steps/os"
	standbysteps "github.com/yinstall/internal/steps/standby"
	stresssteps "github.com/yinstall/internal/steps/stressos"
	winsteps "github.com/yinstall/internal/steps/win_os"
	ycmsteps "github.com/yinstall/internal/steps/ycm"
	ympsteps "github.com/yinstall/internal/steps/ymp"
)

type domain struct {
	Name  string
	Steps func() []*runner.Step
}

var domains = []domain{
	{"os", ossteps.GetAllSteps},
	{"db", dbsteps.GetAllSteps},
	{"standby", standbysteps.GetAllSteps},
	{"om", omsteps.GetAllSteps},
	{"ycm", ycmsteps.GetAllSteps},
	{"ymp", ympsteps.GetAllSteps},
	{"win_os", winsteps.GetAllSteps},
	{"collect", collectsteps.GetAllSteps},
	{"stressos", stresssteps.GetAllSteps},
	{"mysql", mysqlsteps.GetAllSteps},
	{"mysql_standby", mysqlstandbysteps.GetAllSteps},
	{"mssql", mssqlsteps.GetAllSteps},
	{"mssql_ag", mssqlagsteps.GetAGAddSteps},
	{"mssql_mirror", mssqlmirrorsteps.GetMirrorAddSteps},
	{"clean", cleansteps.GetAllSteps},
}

func main() {
	check := flag.Bool("check", false, "validate registry IDs only (no code generation)")
	flag.Parse()

	fail := 0
	for _, d := range domains {
		steps := d.Steps()
		if err := validateSequential(d.Name, steps); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL %s: %v\n", d.Name, err)
			fail++
		}
	}

	if *check {
		if fail > 0 {
			os.Exit(1)
		}
		fmt.Println("stepcatalog --check: OK")
		return
	}

	if fail > 0 {
		fmt.Fprintf(os.Stderr, "stepcatalog: validation failed; fix registries before generate\n")
		os.Exit(1)
	}

	outPath := filepath.Join(repoRoot(), "internal", "runner", "stepcatalog", "catalog_gen.go")
	if err := writeCatalog(outPath); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("stepcatalog: wrote %s\n", outPath)
}

func repoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "."
		}
		wd = parent
	}
}

var reAutoID = regexp.MustCompile(`^([A-Z]+(?:-[A-Z]+)?)-(\d+)$`)

func validateSequential(domain string, steps []*runner.Step) error {
	if len(steps) == 0 {
		return nil
	}
	prefix := ""
	width := 3
	seq := 0
	seenFixed := map[string]bool{}
	for i, s := range steps {
		if s == nil {
			return fmt.Errorf("step[%d] is nil", i)
		}
		if s.ID == "" {
			return fmt.Errorf("step[%d] %q has empty ID", i, s.Name)
		}
		m := reAutoID.FindStringSubmatch(s.ID)
		if m == nil {
			seenFixed[s.ID] = true
			continue
		}
		p := m[1]
		if prefix == "" {
			prefix = p
			if len(m[2]) > 0 {
				width = len(m[2])
			}
		}
		if p != prefix {
			return fmt.Errorf("mixed prefix at %s: want %s got %s", s.ID, prefix, p)
		}
		seq++
		want := fmt.Sprintf("%s-%0*d", prefix, width, seq)
		if s.ID != want {
			return fmt.Errorf("gap at index %d: want %s got %s (%s)", i, want, s.ID, s.Name)
		}
	}
	return nil
}

func writeCatalog(outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/stepcatalog; DO NOT EDIT.\n")
	buf.WriteString("package stepcatalog\n\n")
	buf.WriteString("type Entry struct {\n")
	buf.WriteString("\tDomain string\n")
	buf.WriteString("\tSeq    int\n")
	buf.WriteString("\tID     string\n")
	buf.WriteString("\tName   string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("var Catalog = []Entry{\n")
	for _, d := range domains {
		for i, s := range d.Steps() {
			if s == nil {
				continue
			}
			name := strings.ReplaceAll(s.Name, `"`, `\"`)
			fmt.Fprintf(&buf, "\t{Domain: %q, Seq: %d, ID: %q, Name: %q},\n", d.Name, i+1, s.ID, name)
		}
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, formatted, 0o644)
}
